#ifndef INSTRUCTIONS_LIST_REGULAR_H
#define INSTRUCTIONS_LIST_REGULAR_H

#include "memory.h"
#include "cpu.h"

// 0x00 - 0x0F
void nop(Memory*, CPU*);
void ld_bc_d16(Memory*, CPU*);
void ld_bc_a(Memory*, CPU*);
void inc_bc(Memory*, CPU*);
void inc_b(Memory*, CPU*);
void dec_b(Memory*, CPU*);
void ld_b_d8(Memory*, CPU*);
void rlca(Memory*, CPU*);
void ld_a16_sp(Memory*, CPU*);
void add_hl_bc(Memory*, CPU*);
void ld_a_bc(Memory*, CPU*);
void dec_bc(Memory*, CPU*);
void inc_c(Memory*, CPU*);
void dec_c(Memory*, CPU*);
void ld_c_d8(Memory*, CPU*);
void rrca(Memory*, CPU*);

// 0x10 - 0x1F
void stop(Memory*, CPU*);
void ld_de_d16(Memory*, CPU*);
void ld_de_a(Memory*, CPU*);
void inc_de(Memory*, CPU*);
void inc_d(Memory*, CPU*);
void dec_d(Memory*, CPU*);
void ld_d_d8(Memory*, CPU*);
void rla(Memory*, CPU*);
void jr_s8(Memory*, CPU*);
void add_hl_de(Memory*, CPU*);
void ld_a_de(Memory*, CPU*);
void dec_de(Memory*, CPU*);
void inc_e(Memory*, CPU*);
void dec_e(Memory*, CPU*);
void ld_e_d8(Memory*, CPU*);
void rra(Memory*, CPU*);

// 0x20 - 0x2F
void jr_nz_s8(Memory*, CPU*);
void ld_hl_d16(Memory*, CPU*);
void ld_hli_a(Memory*, CPU*);
void inc_hl(Memory*, CPU*);
void inc_h(Memory*, CPU*);
void dec_h(Memory*, CPU*);
void ld_h_d8(Memory*, CPU*);
void daa(Memory*, CPU*);
void jr_z_s8(Memory*, CPU*);
void add_hl_hl(Memory*, CPU*);
void ld_a_hli(Memory*, CPU*);
void dec_hl(Memory*, CPU*);
void inc_l(Memory*, CPU*);
void dec_l(Memory*, CPU*);
void ld_l_d8(Memory*, CPU*);
void cpl(Memory*, CPU*);

// 0x30 - 0x3F
void jr_nc_s8(Memory*, CPU*);
void ld_sp_d16(Memory*, CPU*);
void ld_hld_a(Memory*, CPU*);
void inc_sp(Memory*, CPU*);
void inc_hlm(Memory*, CPU*);
void dec_hlm(Memory*, CPU*);
void ld_hl_d8(Memory*, CPU*);
void scf(Memory*, CPU*);
void jr_c_s8(Memory*, CPU*);
void add_hl_sp(Memory*, CPU*);
void ld_a_hld(Memory*, CPU*);
void dec_sp(Memory*, CPU*);
void inc_a(Memory*, CPU*);
void dec_a(Memory*, CPU*);
void ld_a_d8(Memory*, CPU*);
void ccf(Memory*, CPU*);

// 0x40 - 0x7F (register-to-register and memory loads)
void ld_b_b(Memory*, CPU*);
void ld_b_c(Memory*, CPU*);
void ld_b_d(Memory*, CPU*);
void ld_b_e(Memory*, CPU*);
void ld_b_h(Memory*, CPU*);
void ld_b_l(Memory*, CPU*);
void ld_b_hl(Memory*, CPU*);
void ld_b_a(Memory*, CPU*);
void ld_c_b(Memory*, CPU*);
void ld_c_c(Memory*, CPU*);
void ld_c_d(Memory*, CPU*);
void ld_c_e(Memory*, CPU*);
void ld_c_h(Memory*, CPU*);
void ld_c_l(Memory*, CPU*);
void ld_c_hl(Memory*, CPU*);
void ld_c_a(Memory*, CPU*);
void ld_d_b(Memory*, CPU*);
void ld_d_c(Memory*, CPU*);
void ld_d_d(Memory*, CPU*);
void ld_d_e(Memory*, CPU*);
void ld_d_h(Memory*, CPU*);
void ld_d_l(Memory*, CPU*);
void ld_d_hl(Memory*, CPU*);
void ld_d_a(Memory*, CPU*);
void ld_e_b(Memory*, CPU*);
void ld_e_c(Memory*, CPU*);
void ld_e_d(Memory*, CPU*);
void ld_e_e(Memory*, CPU*);
void ld_e_h(Memory*, CPU*);
void ld_e_l(Memory*, CPU*);
void ld_e_hl(Memory*, CPU*);
void ld_e_a(Memory*, CPU*);
void ld_h_b(Memory*, CPU*);
void ld_h_c(Memory*, CPU*);
void ld_h_d(Memory*, CPU*);
void ld_h_e(Memory*, CPU*);
void ld_h_h(Memory*, CPU*);
void ld_h_l(Memory*, CPU*);
void ld_h_hl(Memory*, CPU*);
void ld_h_a(Memory*, CPU*);
void ld_l_b(Memory*, CPU*);
void ld_l_c(Memory*, CPU*);
void ld_l_d(Memory*, CPU*);
void ld_l_e(Memory*, CPU*);
void ld_l_h(Memory*, CPU*);
void ld_l_l(Memory*, CPU*);
void ld_l_hl(Memory*, CPU*);
void ld_l_a(Memory*, CPU*);
void ld_hl_b(Memory*, CPU*);
void ld_hl_c(Memory*, CPU*);
void ld_hl_d(Memory*, CPU*);
void ld_hl_e(Memory*, CPU*);
void ld_hl_h(Memory*, CPU*);
void ld_hl_l(Memory*, CPU*);
void ld_hl_a(Memory*, CPU*);
void ld_a_b(Memory*, CPU*);
void ld_a_c(Memory*, CPU*);
void ld_a_d(Memory*, CPU*);
void ld_a_e(Memory*, CPU*);
void ld_a_h(Memory*, CPU*);
void ld_a_l(Memory*, CPU*);
void ld_a_hl(Memory*, CPU*);
void ld_a_a(Memory*, CPU*);
// Forward declarations for arithmetic instructions (0x80-0x9F)
void add_a_b(Memory*, CPU*);
void add_a_c(Memory*, CPU*);
void add_a_d(Memory*, CPU*);
void add_a_e(Memory*, CPU*);
void add_a_h(Memory*, CPU*);
void add_a_l(Memory*, CPU*);
void add_a_hl(Memory*, CPU*);
void add_a_a(Memory*, CPU*);
void adc_a_b(Memory*, CPU*);
void adc_a_c(Memory*, CPU*);
void adc_a_d(Memory*, CPU*);
void adc_a_e(Memory*, CPU*);
void adc_a_h(Memory*, CPU*);
void adc_a_l(Memory*, CPU*);
void adc_a_hl(Memory*, CPU*);
void adc_a_a(Memory*, CPU*);
void sub_b(Memory*, CPU*);
void sub_c(Memory*, CPU*);
void sub_d(Memory*, CPU*);
void sub_e(Memory*, CPU*);
void sub_h(Memory*, CPU*);
void sub_l(Memory*, CPU*);
void sub_hl(Memory*, CPU*);
void sub_a(Memory*, CPU*);
void sbc_a_b(Memory*, CPU*);
void sbc_a_c(Memory*, CPU*);
void sbc_a_d(Memory*, CPU*);
void sbc_a_e(Memory*, CPU*);
void sbc_a_h(Memory*, CPU*);
void sbc_a_l(Memory*, CPU*);
void sbc_a_hl(Memory*, CPU*);
void sbc_a_a(Memory*, CPU*);

//Logical operations (0xA0-0xBF)
void and_b(Memory*, CPU*);
void and_c(Memory*, CPU*);
void and_d(Memory*, CPU*);
void and_e(Memory*, CPU*);
void and_h(Memory*, CPU*);
void and_l(Memory*, CPU*);
void and_hl(Memory*, CPU*);
void and_a(Memory*, CPU*);
void xor_b(Memory*, CPU*);
void xor_c(Memory*, CPU*);
void xor_d(Memory*, CPU*);
void xor_e(Memory*, CPU*);
void xor_h(Memory*, CPU*);
void xor_l(Memory*, CPU*);
void xor_hl(Memory*, CPU*);
void xor_a(Memory*, CPU*);
void or_b(Memory*, CPU*);
void or_c(Memory*, CPU*);
void or_d(Memory*, CPU*);
void or_e(Memory*, CPU*);
void or_h(Memory*, CPU*);
void or_l(Memory*, CPU*);
void or_hl(Memory*, CPU*);
void or_a(Memory*, CPU*);
void cp_b(Memory*, CPU*);
void cp_c(Memory*, CPU*);
void cp_d(Memory*, CPU*);
void cp_e(Memory*, CPU*);
void cp_h(Memory*, CPU*);
void cp_l(Memory*, CPU*);
void cp_hl(Memory*, CPU*);
void cp_a(Memory*, CPU*);

// 0xC0 - 0xDF
void ret_nz(Memory*, CPU*);
void pop_bc(Memory*, CPU*);
void jp_nz_nn(Memory*, CPU*);
void jp_nn(Memory*, CPU*);
void call_nz_nn(Memory*, CPU*);
void push_bc(Memory*, CPU*);
void add_a_n(Memory*, CPU*);
void rst_00h(Memory*, CPU*);
void ret_z(Memory*, CPU*);
void ret(Memory*, CPU*);
void jp_z_nn(Memory*, CPU*);
void prefix_cb(Memory*, CPU*);
void call_z_nn(Memory*, CPU*);
void call_nn(Memory*, CPU*);
void adc_a_n(Memory*, CPU*);
void rst_08h(Memory*, CPU*);
void ret_nc(Memory*, CPU*);
void pop_de(Memory*, CPU*);
void jp_nc_nn(Memory*, CPU*);
void unused_d3(Memory*, CPU*);
void call_nc_nn(Memory*, CPU*);
void push_de(Memory*, CPU*);
void sub_n(Memory*, CPU*);
void rst_10h(Memory*, CPU*);
void ret_c(Memory*, CPU*);
void reti(Memory*, CPU*);
void jp_c_nn(Memory*, CPU*);
void unused_db(Memory*, CPU*);
void call_c_nn(Memory*, CPU*);
void unused_dd(Memory*, CPU*);
void sbc_a_n(Memory*, CPU*);
void rst_18h(Memory*, CPU*);

void ldh_a8_a(Memory* mem, CPU* cpu);
void pop_hl(Memory* mem, CPU* cpu);
void ld__c_a(Memory* mem, CPU* cpu);
void unused_e3(Memory* mem, CPU* cpu);
void unused_e4(Memory* mem, CPU* cpu);
void push_hl(Memory* mem, CPU* cpu);
void and_n(Memory* mem, CPU* cpu);
void rst_20h(Memory* mem, CPU* cpu);
void add_sp_s8(Memory* mem, CPU* cpu);
void jp_hl(Memory* mem, CPU* cpu);
void ld_a16_a(Memory* mem, CPU* cpu);
void xor_n(Memory* mem, CPU* cpu);
void rst_28h(Memory* mem, CPU* cpu);
void ldh_a_a8(Memory* mem, CPU* cpu);
void pop_af(Memory* mem, CPU* cpu);
void ld_a__c(Memory* mem, CPU* cpu);
void di(Memory* mem, CPU* cpu);
void push_af(Memory* mem, CPU* cpu);
void or_n(Memory* mem, CPU* cpu);
void rst_30h(Memory* mem, CPU* cpu);
void ld_hl_sp_s8(Memory* mem, CPU* cpu);
void ld_sp_hl(Memory* mem, CPU* cpu);
void ld_a_a16(Memory* mem, CPU* cpu);
void ei(Memory* mem, CPU* cpu);
void cp_n(Memory* mem, CPU* cpu);
void rst_38h(Memory* mem, CPU* cpu);

#endif